services:
- type: web
  name: typesense
  env: docker
  repo: https://github.com/Elmosh/typesense-on-render.git
  plan: starter
  healthCheckPath: /health
  disk:
    name: typesense-data
    mountPath: /typesense-data
    sizeGB: 1  
  # dockerCommand: >
      # /opt/typesense-server --data-dir /typesense-data --api-key=$TYPESENSE_API_KEY --listen-address=0.0.0.0 --listen-port=8108 --enable-cors
  envVars:
  - key: TYPESENSE_API_KEY
    # generateValue: true
    value: "HhcS39zzROyiKGGV8PLBqyEg7dtk865s7"
  - key: TYPESENSE_DATA_DIR
    value: /typesense-data
  - key: TYPESENSE_ENABLE_CORS
    value: true
  - key: TYPESEMSE_API_ADDRESS
    value: 0.0.0.0
  - key: TYPESEMSE_API_PORT
    value: 8108
  - key: TYPESEMSE_ANALYTICS_FLUSH_INTERVAL
    value: 30
